resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: scaling-diego
  type: git
  source:
    uri: https://github.com/datianshi/scaling-diego.git
    branch: master

- name: pcf-pipelines-tarball
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: pcf-automation
    product_version: v0.16.0

jobs:
- name: scale
  plan:
  - aggregate:
    - do:
      - get: pcf-pipelines-tarball
      - task: unpack-tarball
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: czero/cflinuxfs2
          run:
            path: bash
            args:
            - -c
            - tar -xvf pcf-pipelines-tarball/*.tgz
            dir: ""
          inputs:
          - name: pcf-pipelines-tarball
            path: ""
          outputs:
          - name: pcf-pipelines
            path: ""
    - get: scaling-diego
      trigger: true
  - task: wait-opsman-clear
    file: pcf-pipelines/tasks/wait-opsman-clear/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
  - task: config-diego-instances
    file: scaling-diego/tasks/scaling-diego/task.yaml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      DIEGO_CELL_INSTANCES: {{diego_cell_instances}}
